### ISSUE TITLE
[BUG] Learn More Button on Windows Download Page is Broken

### ISSUE THREAD

**Issue by TheSameCat2** [Redot-Engine/redot-website#13]
### Bug Description

The "Learn More" button on the page located at: https://www.redotengine.org/download/windows is pointing to https://docs-latest.redotengine.org/about/introduction#about-redot-engine instead of https://docs.redotengine.org/en/latest/about/introduction#about-redot-engine which seems to be the correct URL.

### Steps to Reproduce

1. Visit redotengine.org on a Windows computer.
2. Click the "Download" button located in the Hero at the top of the page.
3. Scroll to almost the bottom of the page, look for the heading "What is Redot Engine?"
4. Click the "Learn More ->" button.

### Expected behavior

The introduction page in the latest version of the docs should be loaded.

### Additional Details

Sorry my first submission is so lame. I'm just getting around to checking out Redot and noticed it while I was browsing. :)

Thx to the devs for all the hard work. The page looks absolutely amazing.

### Operating System

Windows 11 - Release Channel - Current

**Comment by charlottewiltshire0** [comment]
The old website will no longer be updated; a new version will be released by the end of the year.

**Comment by charlottewiltshire0** [comment]
This is the repository for the new website; we will take this into account when implementing the download page.

**Comment by charlottewiltshire0** [comment]
This is the repository for the new website; we will take this into account when implementing the download page.
